# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreBitcoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
  # Pods for CoreBitcoin
  pod 'secp256k1.c'
  # Pods for CoreBitcoin

  target 'CoreBitcoinTests' do
    # Pods for testing
  end

end
